services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - .:/app
      # - /app/node_modules # 保留容器内依赖
    env_file:
      - .env.development
    command: npm run dev

  worker:
    build:
      context: .
      target: dev
    env_file:
      - .env.development
